on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
  
    steps:
       - name: executing remote ssh commands using ssh key
         uses: appleboy/ssh-action@v1.0.0
         with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USER }}
           password: ${{ secrets.SSH_PASSWORD }}
           port: ${{ secrets.SSH_PORT }}
           timeout: 1200s
           script: |           
              cd ${{ secrets.WORK_DIR }} 
              echo "aqui esta la variableeeee ${{vars.VITE_API_URL}}"
              git fetch 
              git checkout ${{ secrets.MAIN_BRANCH }} 
              git pull 
              docker stop agenda-front || true
              docker rm agenda-front || true
              docker rmi  municipalidad/agenda-front:latest || true
              docker build --no-cache --pull --build-arg VITE_API_URL=${{vars.VITE_API_URL}} --build-arg VITE_API_URL_GRAFICS=${{vars.VITE_API_URL_GRAFICS}}  -t municipalidad/agenda-front:latest .    
              docker run --restart=always -d -p 0.0.0.0:7013:80 --name agenda-front municipalidad/agenda-front:latest
              exit
